name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build On:(${{ matrix.os }},framework:${{ matrix.framework}})
    runs-on: ${{ matrix.os }}
    env:
      TZ: Asia/Shanghai
    permissions:
      contents: write
      security-events: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        framework: ["assembleLeanbackJavaArm64_v8aRelease",
                    "assembleLeanbackJavaArmeabi_v7aRelease",
                    "assembleLeanbackPythonArm64_v8aRelease",
                    "assembleLeanbackPythonArmeabi_v7aRelease",
                    "assembleMobileJavaArm64_v8aRelease",
                    "assembleMobileJavaArmeabi_v7aRelease",
                    "assembleMobilePythonArm64_v8aRelease",
                    "assembleMobilePythonArmeabi_v7aRelease"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: midsummer0206/oktv20241116
          ref: release
          path: tv

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18


      - name: Checkout Publish sources
        uses: actions/checkout@v4
        with:
          repository: midsummer0206/oktv20241116
          ref: publish
          path: code

      - name: Edit gradle
        run: |
          cd code 
          python build.py --version ${{ github.ref_name }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Release Apk Sign
        run: |
          signingConfigs='ICAgIHNpZ25pbmdDb25maWdzIHtcCiAgICAgICAgaWYgKHByb2plY3QuaGFzUHJvcGVydHkoIlJFTEVBU0VfU1RPUkVfRklMRSIpKSB7XAogICAgICAgICAgICBteUNvbmZpZyB7XAogICAgICAgICAgICAgICAgc3RvcmVGaWxlIGZpbGUoUkVMRUFTRV9TVE9SRV9GSUxFKVwKICAgICAgICAgICAgICAgIHN0b3JlUGFzc3dvcmQgUkVMRUFTRV9TVE9SRV9QQVNTV09SRFwKICAgICAgICAgICAgICAgIGtleUFsaWFzIFJFTEVBU0VfS0VZX0FMSUFTXAogICAgICAgICAgICAgICAga2V5UGFzc3dvcmQgUkVMRUFTRV9LRVlfUEFTU1dPUkRcCiAgICAgICAgICAgICAgICB2MVNpZ25pbmdFbmFibGVkIHRydWVcCiAgICAgICAgICAgICAgICB2MlNpZ25pbmdFbmFibGVkIHRydWVcCiAgICAgICAgICAgICAgICBlbmFibGVWM1NpZ25pbmcgPSB0cnVlXAogICAgICAgICAgICAgICAgZW5hYmxlVjRTaWduaW5nID0gdHJ1ZVwKICAgICAgICAgICAgfVwKICAgICAgICB9XAogICAgfVwKXA=='
          signingConfig='ICAgICAgICAgICAgaWYgKHByb2plY3QuaGFzUHJvcGVydHkoIlJFTEVBU0VfU1RPUkVfRklMRSIpKSB7XAogICAgICAgICAgICAgICAgc2lnbmluZ0NvbmZpZyBzaWduaW5nQ29uZmlncy5teUNvbmZpZ1wKICAgICAgICAgICAgfVwK'
          signingConfigs="$(echo "$signingConfigs" |base64 -d )"
          signingConfig="$(echo "$signingConfig" |base64 -d )"
          sed -i -e "/defaultConfig {/i\\$signingConfigs " -e "/debug {/a\\$signingConfig " -e "/release {/a\\$signingConfig " app/build.gradle
          cp -f ${{ github.workspace }}/.github/workflows/TVBoxOSC.jks app/TVBoxOSC.jks
          sed -i '$a\RELEASE_STORE_FILE=./TVBoxOSC.jks'     ./gradle.properties
          sed -i '$a\RELEASE_KEY_ALIAS=TVBoxOSC'            ./gradle.properties
          sed -i '$a\RELEASE_STORE_PASSWORD=TVBoxOSC'       ./gradle.properties
          sed -i '$a\RELEASE_KEY_PASSWORD=TVBoxOSC'         ./gradle.properties

      - name: Build with Gradle
        run: |
          cd tv
          bash gradlew ${{ matrix.framework}}
      - name: Get Commit Messages
        id: get_git_latest_message
        run: |
          cd tv
          message=$(git log -1 --format=%B HEAD)
          echo "Latest Message is ${message}"
          echo ::set-output name=git_latest::$message
      - name: Get Current Time
        id: get_current_time
        run: |
          current_time=$(date +%F%t%T)
          echo "current_time is ${current_time}"
          echo ::set-output name=current_time::$current_time        
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.fongmi.android.tv
          path: ${{ github.workspace }}/apk/*