name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build On:(${{ matrix.os }},framework:${{ matrix.framework}})
    runs-on: ${{ matrix.os }}
    env:
      TZ: Asia/Shanghai
    permissions:
      contents: write
      security-events: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        framework: ["assembleLeanbackJavaArm64_v8aRelease",
                    "assembleLeanbackJavaArmeabi_v7aRelease",
                    "assembleLeanbackPythonArm64_v8aRelease",
                    "assembleLeanbackPythonArmeabi_v7aRelease",
                    "assembleMobileJavaArm64_v8aRelease",
                    "assembleMobileJavaArmeabi_v7aRelease",
                    "assembleMobilePythonArm64_v8aRelease",
                    "assembleMobilePythonArmeabi_v7aRelease"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          repository: midsummer0206/oktv20241116
          ref: release
          path: tv

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3



      - name: Build with Gradle
        run: |
          cd tv
          bash gradlew ${{ matrix.framework}}
      - name: Get Commit Messages
        id: get_git_latest_message
        run: |
          cd tv
          message=$(git log -1 --format=%B HEAD)
          echo "Latest Message is ${message}"
          echo ::set-output name=git_latest::$message
      - name: Get Current Time
        id: get_current_time
        run: |
          current_time=$(date +%F%t%T)
          echo "current_time is ${current_time}"
          echo ::set-output name=current_time::$current_time        
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.fongmi.android.tv
          path: ${{ github.workspace }}/apk/*